CREATE TABLE TB_ENDERECO(
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
	LOGRADOURO VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(10),
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	MUNICIPIO_IBGE INTEGER,
	UF VARCHAR(2) NOT NULL,	
	PRINCIPAL CHAR(1) NOT NULL,
	ENTREGA CHAR(1) NOT NULL,
	COBRANCA CHAR(1) NOT  NULL,
	CORRESPONDENCIA CHAR(1) NOT NULL,
	CODIGO_PESSOA INTEGER NOT NULL,
	FOREIGN KEY (CODIGO_PESSOA) REFERENCES TB_PESSOA(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_CONTATO(
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	FONE_COMERCIAL VARCHAR(10),
	FONE_RESIDENCIAL VARCHAR(10),
	FONE_CELULAR VARCHAR(11),	
	CODIGO_PESSOA INTEGER NOT NULL,
	FOREIGN KEY (CODIGO_PESSOA) REFERENCES TB_PESSOA(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_TELEFONE(
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
	TIPO_TELEFONE VARCHAR(20) NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
	OBSERVACAO VARCHAR(255),
	CODIGO_PESSOA INTEGER NOT NULL,
	FOREIGN KEY (CODIGO_PESSOA) REFERENCES TB_PESSOA(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

