CREATE TABLE TB_ESTADO_CIVIL (
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_PESSOA_FISICA (
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
	CPF VARCHAR(20) NOT NULL,
	RG VARCHAR(20) NOT NULL,
	ORGAO_RG VARCHAR(10),
	DATA_EMISSAO_RG DATE,
	DATA_NASCIMENTO DATE NOT NULL,
	TIPO_SEXO CHAR(1) NOT NULL,
	NATURALIDADE VARCHAR(50),
	NACIONALIDADE VARCHAR(50),
	TIPO_RACA VARCHAR(20),
	TIPO_SANGUE VARCHAR(10),
	CNH_NUMERO VARCHAR(20),
	CNH_CATEGORIA VARCHAR(5),
	CNH_VENCIMENTO DATE,
	TITULO_ELEITORAL_NUMERO VARCHAR(20),
	TITULO_ELEITORAL_ZONA INTEGER,
	TITULO_ELEITORAL_SESSAO INTEGER,
	RESERVISTA_NUMERO VARCHAR(30),
	RESERVISTA_CATEGORIA INTEGER,
	NOME_MAE VARCHAR(100),
	NOME_PAI VARCHAR(100),
	CODIGO_ESTADO_CIVIL INTEGER NOT NULL,
	CODIGO_PESSOA INTEGER NOT NULL,
	FOREIGN KEY (CODIGO_ESTADO_CIVIL) REFERENCES TB_ESTADO_CIVIL(CODIGO),
	FOREIGN KEY (CODIGO_PESSOA) REFERENCES TB_PESSOA(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_PESSOA_JURIDICA (
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
	CNPJ VARCHAR(30) NOT NULL,
	NOME_FANTASIA VARCHAR(150) NOT NULL,
	INSCRICAO_MUNICIPAL VARCHAR(30),
	INSCRICAO_ESTADUAL VARCHAR(30),
	DATA_CONSTITUICAO DATE,
	TIPO_REGIME VARCHAR(30),
	TIPO_CRT VARCHAR(20),
	SUFRAMA VARCHAR(150),
	CODIGO_PESSOA INTEGER,
	FOREIGN KEY (CODIGO_PESSOA) REFERENCES TB_PESSOA(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;